services:


  view:
    container_name: view
    build:
      context: ./view
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./view:/app
    command: ["sh", "-c", "pnpm install && pnpm run dev"]
    environment:
      NODE_ENV: development
      API_URL: http://localhost:8000

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./db://var/lib/pgadmin

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: example@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db

  terminal:
    container_name: terminal
    ports:
      - "8080:8080"
    build:
      context: ./terminal
      dockerfile: Dockerfile
    read_only: true  # ここでファイルシステムを読み取り専用に設定

