name: CI-terminal

on:
  pull_request:
    paths:
        - 'terminal/**'
        - '.github/workflows/ci-terminal.yml'

jobs:
  check-security-for-Trivy:
    runs-on: ubuntu-latest

    steps:
      # GitHubリポジトリのコードをチェックアウト
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: true

      # Docker Buildxのセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # 永続ビルダー設定
        with:
          install: true
          buildkitd-flags: --debug

      # dockerをbuild
      - name: Build and push Docker image
        run: |
          docker build \
          --pull \
          --platform linux/amd64 \
          -f terminal/Dockerfile \
          -t hp-terminal:${{ github.sha }} \
          terminal

      # Docker Buildxのキャッシュをプルーニング
      - name: Prune Buildx builder and caches
        if: always()
        run: |
          docker buildx prune --all --force


      # Trivyでイメージのセキュリティチェック
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'hp-terminal:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
